name: ci

on:
  push

jobs:
  build-windows:
    runs-on: windows-2019
    name: build windows binary

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Build exe binary and archive
        shell: cmd
        run: |
          cd .\src\client
          sed -e "s/\"\[v.*semver$/\"[test-${{ github.sha }}]\"/" -i.bak yobot.py
          pip install -r requirements.txt
          pip install pyinstaller
          PYTHONOPTIMIZE=0
          pyinstaller main.spec

      - uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: ./src/client/dist/yobot.exe
